---
- name: Pull Docker Image of Calculator
  hosts: all
  tasks:
    - name: Pull image
      docker_image:
        name: menkchad/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker create -it --name Calculator menkchad/calculator